language: rust
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - libasound2-dev
    
rust:
  - stable

cache: cargo

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - cargo install-update -a # update outdated cached binaries

# the main build
script:
  - |
      cargo build &&
      cargo test &&
      cargo bench &&
      cargo doc

after_success: 
  - |
      curl -O https://raw.githubusercontent.com/cmsd2/travis-doc-upload/master/travis-doc-upload.sh &&
      sh -x travis-doc-upload.sh